language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw

branches:
  only:
    - master
    - dev

cache:
  directories:
  - $HOME/.m2

script:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - ./mvnw test -B -X